### ISSUE TITLE
Create page with [downloads] during registration

### ISSUE THREAD

**Issue by pippinsplugins** [SellBirdHQ/sellbird#13]
When new accounts are registered, we need to create a page on the new site that contains `[downloads]` in order for the store to display a person's products.

This page should also get set as the front page.

**Comment by DrewAPicture** [comment]
Added a PR to rcp-site-creation to fire an action following site creation, upon which we can hook things like a routine to add a page with the `[downloads]` shortcode in it.

PR: https://github.com/restrictcontentpro/rcp-site-creation/issues/33

**Comment by pippinsplugins** [comment]
RCP Site Creation PR merged.

**Comment by DrewAPicture** [comment]
PR: #26
