### ISSUE TITLE
Set EDD checkout to "distraction-free"  template during product checkout

### ISSUE THREAD

**Issue by pippinsplugins** [SellBirdHQ/sellbird#14]
The `themedd` theme (which `sellbird-store` is based on) includes a special option for "Distraction free checkout".

This should be enabled on the site during account creation.

This may actually just be a change that is done inside of the sellbird-store theme. @amdrew ?

**Comment by amdrew** [comment]
@pippinsplugins 👍 Yeah, we can do that in the theme by just copying the `themedd_edd_set_distraction_free_checkout()` pluggable function and then removing the check for the admin option. 

Maybe I should add a filter though, would be much easier than duplicating code.

**Comment by DrewAPicture** [comment]
Moved to https://github.com/SellBirdHQ/theme-store/issues/1
