### ISSUE TITLE
Build out complete product edit screen

### ISSUE THREAD

**Issue by pippinsplugins** [SellBirdHQ/sellbird#19]
The current edit screen has just enough fields to make basic products but we'll need more before this is ready for MVP.

I think we should start with the following:

- [ ] Image upload field for the main product image
- [ ] Multiple price options (repeatable row similar to EDD admin) with name and amount for each
- [ ] Product name
- [ ] Product description with rich editor
- [ ] Product excerpt (maybe?)
- [ ] Product files with upload (repeatable row like EDD core's admin)

**Comment by DrewAPicture** [comment]
Moved to https://github.com/SellBirdHQ/theme/issues/17
