### ISSUE TITLE
Stripe Connect integration during account registration

### ISSUE THREAD

**Issue by pippinsplugins** [SellBirdHQ/sellbird#20]
[Stripe Connect](https://stripe.com/connect) is the system we will use to connect store owner accounts with our main Stripe account. This, among other things, allows us to:

- Create Stripe accounts on behalf of store owner's (also allows connecting existing accounts)
- Take a small percentage and/or flat fee of each transaction processed through stores
- See volume reports of all store owners (saves us building extensive reporting)
- Provides the means to process card payments from customers

The account registration flow will be something like this:

1. Register for account on sellbird.com (goes through RCP)
2. Subsite is created for account owner in our multisite network
3. Account owner lands in their dashboard and are given the option to create products and set up their various store settings (description, logo, etc)
4. A banner notice is shown to indicate their store is in "pending" or "test" mode and they need to go live before they can start selling
5. To go live, account owner clicks on a button that sends them through the Stripe Connect oauth flow
6. Once oauth is complete, account owner lands back on sellbird.com and their account is switched to live mode

With Stripe Connect, we actually have three different types of accounts we can use:

- Standard
- Express
- Custom

Each has their own pros and cons and we'll need to decide exactly which one we want to use. Please review Stripe's description of them: https://stripe.com/docs/connect/accounts

While choosing the account type we want to use, we also need to consider the pricing differences: https://stripe.com/us/connect/pricing

[Connect documentation](https://stripe.com/docs/connect).

**Comment by DrewAPicture** [comment]
Moved to https://github.com/SellBirdHQ/theme/issues/18
