### ISSUE TITLE
Enable Stripe gateway for new stores

### ISSUE THREAD

**Issue by DrewAPicture** [SellBirdHQ/sellbird#32]
The EDD Stripe gateway needs to be enabled for new stores automatically. To do this we just need to filter the list of enabled gateways and add Stripe.

Filter is called `edd_enabled_payment_gateways` and it receives an array of key value pairs. Adding Stripe as an enabled gateway just requires that `'stripe' => 'Stripe'` be added to the array.

Previously: SellBirdHQ/theme/issues/72

**Comment by DrewAPicture** [comment]
Code we can use:
```php
add_filter( 'edd_enabled_payment_gateways', function( $gateways ) {
	$gateways['stripe'] = 'Stripe';

	return $gateways;
} );
```

**Comment by amdrew** [comment]
I needed this so have added it to the plugin as suggested above:
https://github.com/SellBirdHQ/sellbird/pull/33

Works great.

**Comment by DrewAPicture** [comment]
This is now handled in latest `master` in the platform plugin.
