### ISSUE TITLE
Add product edit screen

### ISSUE THREAD

**Issue by pippinsplugins** [SellBirdHQ/sellbird#6]
We need stores to be able to edit their products.

For now the edit screen should match the add new product screen.

**Comment by DrewAPicture** [comment]
Started a PR: #17

**Comment by DrewAPicture** [comment]
@pippinsplugins This PR is ready for review. You can access the product edit URL via the Edit link in the Products table. It follows the pattern "/dashboard/products/edit/##" and you'll need to flush your rewrites to test.

**Comment by pippinsplugins** [comment]
Hmm, actually it's not working on live. Just noticed why.

The edit URl being given is `http://pippins-ebooks.sellbird.com/dashboard/products/edit/8` but it should be just `http://sellbird.com/dashboard/products/edit/8`.

**Comment by pippinsplugins** [comment]
Without the sub domain everything works fine.

**Comment by pippinsplugins** [comment]
Let's also leave this open as a general holding issue for the complete product edit screen. There are additional items to add to it still.

**Comment by DrewAPicture** [comment]
Possibly because the store switching might not be having an effect on the current site URL?

**Comment by pippinsplugins** [comment]
Edit and add screens live on the main network site, not one one of the subsites, so the function to get the edit URL should not switch to the sub site.

**Comment by DrewAPicture** [comment]
@pippinsplugins I just pushed two commits to `master` ^, one to fix the edit URL and the other to ensure the edit product template respects the current store.

**Comment by pippinsplugins** [comment]
Looks great now!
